apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::251557857946:user/jenkins
      username: jenkins
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::251557857946:role/UdacityCapStone-Worker-Node-NodeInstanceRole-CXY3N2NPCVLQ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
