Description: >
  Felix Geelhaar / Udacity Project Capstone
  This template defines the K8S cluster

Parameters:
  StackName:
    Type: String
    Description: The name of the Stack.

  ClusterName:
    Description: The name of the cluster.
    Type: String

  Subnets:
    Description: The subnets where workers can be created.
    Type: String

  SecurityGroup:
    Description: The security group of the cluster control plane.
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  KubernetesCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          Fn::Split:
            - ","
            - !Ref Subnets
      RoleArn: !GetAtt ClusterRole.Arn

Outputs:
  K8SCluster:
    Description: The K8S Cluster Name
    Value: !Ref KubernetesCluster
    Export:
      Name: !Sub "${StackName}-Cluster"
